services:
  api:
    build:
      context: ./src/AuthService.Api
      dockerfile: Dockerfile
    ports:
      - "5226:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=authdb;Username=postgres;Password=clave123
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=clave123
      - POSTGRES_DB=authdb
    ports:
      - "5432:5432"
